# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "iridium"
version = "0.1.0"
rust-version = "1.68"
edition = "2021"

[dependencies]
nalgebra = "*"
rand = "*"
sfml = "0.20.*"

[profile.dev]
opt-level = 1
