[package]
name = "iridium"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
nalgebra = "0.10.*"
rand = "0.8.5"
winit = "0.27.5"
bytemuck = "1.12.3"
vulkano = "0.32.0"
vulkano-win = "0.32.0"
vulkano-shaders = "0.32.0"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["ttf", "image", "gfx", "mixer"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
